language: c
sudo: false

matrix:
  include:
    - compiler: gcc
      env: CODECOV='1.6.3'
    - compiler: gcc
      env: COMPILER='gcc-5'
      addons:
        apt:
          sources: ubuntu-toolchain-r-test
          packages: gcc-5
    - compiler: gcc
      env:
        - COMPILER='i686-w64-mingw32-gcc'
        - UPX='3.91'
      addons:
        apt:
          packages:
            - gcc-mingw-w64-i686
            - binutils-mingw-w64-i686
    - compiler: gcc
      env:
        - COMPILER='x86_64-w64-mingw32-gcc'
        - UPX='3.91'
      addons:
        apt:
          packages:
            - gcc-mingw-w64-x86-64
            - binutils-mingw-w64-x86-64
    - compiler: clang

install:
  - if [ "$CC" = 'clang' ]; then
      export CC=`which clang`;
    fi
  - if [ -n "$CODECOV" ]; then
      pip install --user codecov;
    fi

before_script:
  - make PREFIX=~ bootstrap
  - export MILKYC=~/bin/milky
  - if [ -n "$COMPILER" ]; then
      export CC="$COMPILER";
      $CC --version;
    fi

script:
  - if [[ "$CC" =~ 'mingw' ]]; then
      export TARGET=milky-${CC%-gcc}.exe;
      make release;
    else
      make test;
    fi

after_success:
  - if [ -n "$CODECOV" ]; then
      make clean;
      make coverage;
      bin/milky src/*.k;
      make dummy;
      rm -rf src;
      mv obj/src ./;
      wget "https://github.com/codecov/codecov-python/archive/v${CODECOV}.tar.gz";
      tar -xzvf v${CODECOV}.tar.gz;
      export CODECOV=codecov-python-${CODECOV}/codecov/__init__.py;
      sed -i "s:\(write('==> \)\(Upload\)\(ing')\):\1Overwrit\3;\
        reports = re.sub('(src[#/]'\
        '\\\\\\\\\w+\\\\\\\\.c)(?\!\\\\\\\\.k)', '\\\\\\\\1.k', \
        reports);\1\2\3:" ${CODECOV};
      python ${CODECOV} --gcov-args '-o obj';
    fi

before_deploy:
  - if [ -n "$UPX" ]; then
      export UPX=upx-${UPX}-amd64_linux;
      wget "http://upx.sourceforge.net/download/${UPX}.tar.bz2";
      tar --strip-components=1 -xjvf ${UPX}.tar.bz2 ${UPX}/upx;
      unset UPX;
      ./upx bin/$TARGET;
    fi

deploy:
  provider: releases
  api_key:
    secure: SgSoNQnZWLn5hp80hNpuP9mVRwWvGQauTZi6ISflme33IykeMdn4F2/dhLeogAn6HmzrLXqZPn5rKLEaD5nfm5f7q9uc5ztLyPuMA0j3hknpUHHLFOU8QKMNYEsY71Af1crOU4PTjxxAi8vJAaas1u+JnWqzspoxXxuxGGG2fbY=
  skip_cleanup: true
  file: bin/$TARGET
  on:
    tags: true
    condition: $TARGET
