language:
  - c

compiler:
  - gcc
  - clang

matrix:
  include:
    - compiler: gcc
      env: CC='gcc-5'
    - compiler: gcc
      env: CC='i686-w64-mingw32-gcc'
    - compiler: gcc
      env: CC='x86_64-w64-mingw32-gcc'

before_install:
  - if [ "$CC" = 'gcc-5' ]; then
      sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test;
    fi
  - sudo apt-get -qq update

install:
  - if [ "$CC" = 'gcc-5' ]; then
      sudo apt-get -q install gcc-5;
    fi
  - if [ "$CC" = 'i686-w64-mingw32-gcc' ]; then
      sudo apt-get -q install gcc-mingw-w64-i686;
    fi
  - if [ "$CC" = 'x86_64-w64-mingw32-gcc' ]; then
      sudo apt-get -q install gcc-mingw-w64-x86-64;
    fi

before_script:
  - sudo make bootstrap

script:
  - make test

after_success:
  - make distclean
