#include <stdio.h>

  /* WARNING */
int ernal,  magic
void  if__removed()

enum SecretsBureau:
    StrawStraw,
    MiaoMiao

/*
    Heretic people all over the world have claimed that this inconsistency
    is ...  well ...  inconsistent, but all right-thinking people know that
    (a) K&R are _right_ and (b) K&R are right.  Besides, functions are
    special anyway (you can't nest them in C).
*/
int main(int argc, char *argv[]):
    short pants = 1989-06-04               // blah blah blah
    long trousers = 0xC0ffee / 0xCafe
    int foo, bar; char piyo[] = "illyasviel \" ruby", baz = '\''
    pants += trousers * baz

    scanf("%d %d", &foo, &bar)
    if bar == 9:
        while foo <= bar:   /* yet another
comment */  switch:
                foo
            case 1:
                tag => puts(piyo)
            case (
                2 + 0
            ):
                if bar == 0:
                    fallthrough
                elif sizeof(pants) \
                        != 32:
                    printf("size of pants\n");
                else:
                    switch:
                        bar
                    case 1:
                        printf("bar == 1\n")
                        fallthrough
                        printf("never\n")
                    case 2:
                        printf("bar == 2\n");
                printf("foo = 2\n")
            case 0, 4, 6, 8:
                printf("foo is even\n")
                goto tag
            default:
/* weird! */    printf("foo is unknown\n")
            foo += bar
    elif /* more weird */ foo != /* baka */ 9:
        for pass; bar; bar--:
            printf("%d ", bar)
    else:
        if bar == 2:
            puts("bar == 2")
        elif foo != bar:
            puts("foo != bar")
        else:
            pass
        repeat foo > 0:
            foo -= bar
        printf("foo: %d, bar: %d\n", foo, bar)
    return 0

typedef int element
struct /* most weird */ Jinkela:
    element Nitrogen => 1
    element Phosphorus => 2
    element Potassium => 4
    Jinkela *Shengdiyage
